#!/usr/bin/env bash
set -euo pipefail
: "${VAST_HOST:?set VAST_HOST=user@host}"
: "${VAST_ROOT:?set VAST_ROOT=/workspace/g05-run}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
: "${G05_ROOT:?set local G05_ROOT to the external G0.5 checkout}"
: "${G05_BASE_ASSETS:?set G05_BASE_ASSETS to downloaded official assets}"
DATASET="${ROBODOJO_LEROBOT_V30_ROOT:-${ROOT}/data/lerobot_v30_joint}"
SIDECAR="${ROBODOJO_SIDECAR:-/mnt/pqssd/RoboInter/RoboInterTools/annotations/lerobot_v30_joint.sqlite3}"
rsync -a --partial --info=progress2 --delete-delay "${ROOT}/" "${VAST_HOST}:${VAST_ROOT}/RoboDojo/"
rsync -a --partial --info=progress2 --delete-delay "${G05_ROOT}/" "${VAST_HOST}:${VAST_ROOT}/G05/"
rsync -a --partial --info=progress2 --delete-delay "${G05_BASE_ASSETS}/" "${VAST_HOST}:${VAST_ROOT}/base_assets/"
rsync -a --partial --info=progress2 --delete-delay "${DATASET}/" "${VAST_HOST}:${VAST_ROOT}/data/lerobot_v30_joint/"
rsync -a --partial --info=progress2 "${SIDECAR}" "${VAST_HOST}:${VAST_ROOT}/annotations/"
ssh "${VAST_HOST}" "cd '${VAST_ROOT}/RoboDojo' && ROBODOJO_LEROBOT_V30_ROOT='${VAST_ROOT}/data/lerobot_v30_joint' ROBODOJO_SIDECAR='${VAST_ROOT}/annotations/$(basename "${SIDECAR}")' bash scripts/g05/make_manifest.sh artifacts/g05_robodojo"
ssh "${VAST_HOST}" "cd '${VAST_ROOT}' && bash RoboDojo/scripts/g05/full_manifest.sh transfer.manifest.sha256 RoboDojo G05 data/lerobot_v30_joint annotations base_assets"
echo "Sync complete. Run preflight on VastAI before training."
